name: Lint and build
on:
  pull_request:
    branches:
      - main

jobs:
  lint: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node 
        uses: actions/setup-node@v3
      
      - name: Setup pnpm 
        run: corepack enable

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build 
