name: Release
on: 
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  lint:
    uses: TanishqSingla/ketu/.github/workflows/ci.yml@main

  publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node 
        uses: actions/setup-node@v3

      - name: Publish package
        run: npm publish
