name: Release
on: 
  release:
    types:
      - published

jobs:
  lint:
    uses: TanishqSingla/ketu/.github/workflows/ci.yml@main

  publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Publish package
        run: npm publish
