name: Release
on: 
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish-build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node 
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      
      - name: Setup pnpm 
        run: corepack enable && corepack prepare pnpm@9.15.3 --activate 

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build 

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
