name: Release
on: 
  release:
    types:
      - published

jobs:
  lint:
    uses: https://github.com/TanishqSingla/ketu/blob/main/.github/workflows/ci.yml

  publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Publish package
        run: npm publish
